### ISSUE TITLE
Several compilation issues

### ISSUE THREAD

**Issue by anikristo** [ips4o/ips4o-benchmark-suite#1]
Hi! 
I ran into the following compilation issues when I was trying to use the code:

1. All the files under the src/algorithm directory throw a compilation error due to missing <chrono> library. As a workaround, I added the line `#include <chrono>` in the src/datatypes.hpp file, which is included by all the benchmark files, and it worked.
<img width="654" alt="Screen Shot 2020-11-30 at 17 45 33" src="https://user-images.githubusercontent.com/6381903/100675533-20b5ca00-3335-11eb-8a58-91398a2ffca0.png">

2. The file src/algorithm/stdsort.hpp throws a compilation error at the call of std::sort() since that function is included in the <algorithms> header. To fix it, you should add `#include <algorithm>` in that file. 

3. The file src/benchmark/benchmark_yaroslavskiy.cpp throws a compilation error due to a missing closing brace in the main function.

My environment: 
- OS: Linux Ubuntu 20.04, kernel 5.4.0-26-generic
- Compiler: gcc version 11.0.0 20201024 (experimental) (GCC)  --> configured with Cilkplus

**Comment by ips4o** [comment]
Thank you for your report. All issues should have been fixed.
