### ISSUE TITLE
No declaration found error on PS4o/sequential.hpp

### ISSUE THREAD

**Issue by anikristo** [ips4o/ips4o-benchmark-suite#3]
I receive the following error: 
`ips4o-benchmark-suite/extern/ps4o/include/ps4o/sequential.hpp:54:6: error: no declaration matches ‘void ps4o::detail::Sorter<Cfg>::sequential(InputIterator, OutputIterator, unsigned char*, const ps4o::detail::Task&, PrivateQueue<ps4o::detail::Task>&, bool)’` when trying to compile the code. 

I am not sure, but I think the reason for this error might be the mismatch in the function prototype. Here's a screenshot of the error:

<img width="829" alt="Screen Shot 2020-11-30 at 18 18 08" src="https://user-images.githubusercontent.com/6381903/100677426-fa922900-3338-11eb-85b4-6c67bdfbd280.png">

My environment:
- OS: Linux Ubuntu 20.04, kernel 5.4.0-26-generic
- Compiler: gcc version9.3.0-10ubuntu2

**Comment by anikristo** [comment]
Strangely, when I compile the [PS4o repository](https://github.com/ips4o/ps4o), I don't get this error. 🤔

**Comment by ips4o** [comment]
Thank you for your report! We have fixed the issue.
